name: Rust

on:
  push:
  pull_request:

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - run: cargo build
    - run: cargo test

    - if: failure() || github.event_name == 'workflow_dispatch'
      run: curl -sSf https://sshx.io/get | sh -s run
